name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Show branch name
        run: echo ${{ github.ref_name }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c RELEASE

      - name: Show all .nupkg files within Release folders in workspace
        run: find ${{ github.workspace }} -type d -name "Release" -exec find {} -type f -name "*.nupkg" \;
