name: Build and deploy docs
on:
  push:
    branches: [ main ]
    
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore
          
      - uses: nunit/docfx-action@v3.4.2
        name: Build Documentation
        with:
          args: docs/docfx.json
          
      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
          BUILD_DIR: _site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.PAT_TOKEN }} # See https://github.com/maxheld83/ghpages