name: Build and deploy docs
on:
  push:
    branches: [ main ]
    
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Setup DocFX
        run: dotnet tool install -g docfx

      - name: Install dependencies
        run: dotnet restore

      - name: DocFX Build
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false
        
      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true