name: Build and deploy docs
on:
  push:
    branches: [ main ]
    
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          
      - uses: nunit/docfx-action@v2.4.0
        name: Build Documentation
        with:
          args: docs/docfx.json
          
      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
          BUILD_DIR: docs/_site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.PAT_TOKEN }} # See https://github.com/maxheld83/ghpages